const { pool } = require("../config/database");
const { faker } = require("@faker-js/faker");

const tableName = "res_agents";

const agents = [
  {
    id: 4,
    logo: "Apnagsm logo.png",
    name: "Apna Gsm",
    address: "india",
    phone: "",
    whatsapp: "+918393015038",
    telegram: "https://telegram.me/apnagsm",
    email: "",
    website: "https://apnagsm.com/",
    description: "<p>Worldwide/Distributor</p>",
    country_code: "IN",
  },
  {
    id: 5,
    logo: "ZSGsmServer.png",
    name: "ZsMalikTeam",
    address: "New Delhi India",
    phone: "+91905878778",
    whatsapp: "+917710779696",
    telegram: "https://t.me/ZsGsmServer",
    email: "",
    website: "https://zsgsmserver.com/",
    description: "<p>official Reseller</p>",
    country_code: "IN",
  },
  {
    id: 6,
    logo: "WhatsApp Image 2023-10-23 at 09.56.40.jpeg",
    name: "Gsm Pyarelal",
    address: "india",
    phone: "",
    whatsapp: "+919525383759",
    telegram: "https://telegram.me/GsmPyarelal",
    email: "",
    website: "",
    description: "<p>official Reseller</p>",
    country_code: "IN",
  },
  {
    id: 8,
    logo: "download.jfif",
    name: "FarhazGsm",
    address: "india",
    phone: "",
    whatsapp: "9456289577",
    telegram: "@gsmflake",
    email: "",
    website: "https://www.gsmflake.com/",
    description: "",
    country_code: "IN",
  },
  {
    id: 9,
    logo: "77181c54-b152-4564-995b-3a3bf5192667.jpg",
    name: "Gsm Shukla Technology",
    address: "Saudi Arabia/India",
    phone: "",
    whatsapp: "+966557067640/+917880760912",
    telegram: "https://t.me/Gsm_Shukla",
    email: "",
    website: "",
    description: "<p>Reseller</p>",
    country_code: "IN",
  },
  {
    id: 11,
    logo: "WhatsApp Image 2024-02-12 at 08.00.39.jpeg",
    name: "SANMUKHA",
    address: "Andhra Pradesh, India",
    phone: "",
    whatsapp: "+918187845143",
    telegram: "GsmFastUnlock_Support",
    email: "",
    website: "https://www.gsmfastunlock.com/",
    description: "<p>Reseller</p>",
    country_code: "IN",
  },
  {
    id: 12,
    logo: "LOGO-Small2.jpg",
    name: "RAJENDRA SAINI",
    address: "Delhi (INDIA)",
    phone: "",
    whatsapp: "+918178754944",
    telegram: "https://t.me/RajendraSaini1020",
    email: "",
    website: "https://www.Gsmstore.in",
    description: "<p>Reseller</p>",
    country_code: "IN",
  },
  {
    id: 19,
    logo: "umt.PNG",
    name: "Ashik khan",
    address: "Bangladesh",
    phone: "",
    whatsapp: "+8801856213291",
    telegram: "@sourceforapple",
    email: "",
    website: "https://sourceforapple.com/",
    description: "<p>Reseller</p>",
    country_code: "BD",
  },
  {
    id: 20,
    logo: "WhatsApp Image 2024-11-03 at 14.02.37.jpeg",
    name: "Hasan ali",
    address: "West Bengal",
    phone: "",
    whatsapp: "+917001864497",
    telegram: "",
    email: "",
    website: "",
    description: "<p>Reseller</p>",
    country_code: "IN",
  },
  {
    id: 21,
    logo: "af3cf467-340e-47cf-9603-0d4a8858c463.jfif",
    name: "GsmDBTserver",
    address: "Nepal",
    phone: "",
    whatsapp: "+9779869748283",
    telegram: "https://t.me/Gsmdbtserver_official",
    email: "",
    website: "https://gsmdbtserver.com",
    description: "<p>Official Reseller in Nepal</p>",
    country_code: "NP",
  },
  {
    id: 22,
    logo: "WhatsApp Image 2024-11-24 at 17.16.49_f6483098.jpg",
    name: "hxrugsm.com",
    address: "Russia",
    phone: "",
    whatsapp: "+79110745808",
    telegram: "@hxruofficial",
    email: "",
    website: "http://hxrugsm.com",
    description: "<p>Reseller</p>",
    country_code: "RU",
  },
  {
    id: 24,
    logo: "WhatsApp Image 2024-12-30 at 17.20.23_8004e790.jpg",
    name: "SHRESHTH MOBILE",
    address: "INDIA",
    phone: "",
    whatsapp: "+918563958500",
    telegram: "https://telegram.me/SHRESHTHMOBILE",
    email: "",
    website: "",
    description: "<p>official Reseller</p>",
    country_code: "IN",
  },
  {
    id: 25,
    logo: "ramraj.PNG",
    name: "Ramraj Repair Tools",
    address: "New Delhi India",
    phone: "+91930000663",
    whatsapp: "+919300006632",
    telegram: "",
    email: "",
    website: "http://www.ramrajrepairtools.com",
    description: "",
    country_code: "IN",
  },
  {
    id: 26,
    logo: "WhatsApp Image 2025-01-05 at 12.57.37_4df91c6b.jpg",
    name: "Prem_India",
    address: "INDIA - WORLDWIDE",
    phone: "+91989716144",
    whatsapp: "+919897161446",
    telegram: "https://t.me/GsmPride",
    email: "",
    website: "http://www.gsmpride.com",
    description: "",
    country_code: "IN",
  },
  {
    id: 27,
    logo: "WhatsApp Image 2025-01-10 at 17.16.58_62606d27.jpg",
    name: "GsmFastunloking",
    address: "",
    phone: "+91915152417",
    whatsapp: "+919151524175",
    telegram: "https://t.me/gsmfastunlockingg",
    email: "",
    website: "https://gsmfastunlocking.com",
    description: "",
    country_code: "IN",
  },
  {
    id: 28,
    logo: "GSM24SEVEN_LOGO_MOCKUP_3.png",
    name: "GSM 24SEVEN",
    address: "Delhi India",
    phone: "+91889927410",
    whatsapp: "+918899274100",
    telegram: "https://t.me/GSM24SEVEN",
    email: "",
    website: "https://www.gsm24seven.com/",
    description: "",
    country_code: "IN",
  },
];  

// Function to migrate table and insert data
async function migrateTable() {
  try {
   
    for (let agent of agents) {
      await pool.query(
        `INSERT INTO ${tableName} (name, phone, email, logo, description, address, website, telegram, whatsapp, country_code) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        [
          agent.name,
          agent.phone,
          agent.email,
          agent.logo,
          agent.description,
          agent.address,
          agent.website,
          agent.telegram,
          agent.whatsapp,
          agent.country_code,
        ]
      );
    }

    console.log("Site options migrated successfully!");
  } catch (error) {
    console.error("Error migrating site options:", error);
  } finally {
    process.exit();
  }
}

// Run migration
migrateTable();
