name: Auto Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy App to VPS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          cd /root/myapp
          git pull origin main
          npm install
          pm2 restart app
