name: Deploy Node.js App to cPanel

on:
  push:
    branches:
      - main  # Triggers deployment when changes are pushed to the main branch

jobs:
  deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install lftp
      run: sudo apt-get install -y lftp

    - name: Deploy files via FTP
      env:
        FTP_SERVER: ftp.mathematicalpathshala.in
        FTP_USERNAME: mukesh@api.paidfirmware.com
        FTP_PASSWORD: kPwr~~!(Yi1-
        FTP_PATH: /
      run: |
        lftp -f "
        set ssl:verify-certificate no
        open ftp://$FTP_USERNAME:$FTP_PASSWORD@$FTP_SERVER
        lcd .
        cd $FTP_PATH
        mirror --reverse --verbose --no-delete --only-newer ./ .
        bye
        "
