name: Auto Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy App to VPS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          cd /root/myapp

          # Cleanly reset code to match GitHub repo
          git fetch origin main
          git reset --hard origin/main
          git clean -fd

          # Install dependencies
          npm install

          # Restart the app using PM2
          pm2 restart app
