name: Deploy Node.js App to cPanel

on:
  push:
    branches:
      - main  # Triggers deployment when changes are pushed to the main branch

jobs:
  deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy files via FTP
      env:
        FTP_SERVER: ftp.mathematicalpathshala.in
        FTP_USERNAME: mukesh@api.paidfirmware.com
        FTP_PASSWORD: kPwr~~!(Yi1-
        FTP_PATH: /
      run: |
        # Change to the directory where the files are located
        cd . 
        
        # Upload files using curl
        for file in *; do
          curl -T "$file" ftp://$FTP_USERNAME:$FTP_PASSWORD@$FTP_SERVER$FTP_PATH"$file"
        done
